# Generated by Django 2.0.3 on 2018-06-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_truefalsequestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='questions',
            new_name='total_questions',
        ),
    ]
